name: Upload to Modrinth

on:
  push:
    branches:
      - 'main'

jobs:
  upload-mod:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm install -g mc-ezpack
      - run: npm install
        working-directory: ./scripts
      - name: Create env file
        run: |
          touch .env
          echo token=${{ secrets.MODRINTH }} >> .env
          echo commit_message=${{ secrets.github.event.head_commit.message }} >> .env
        working-directory: ./scripts
      - run: node upload-modrinth.js
        working-directory: ./scripts